
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team03-s23-5pm-3
owner: ucsb-cs156-s23
repo_name: team03-s23-5pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjcyODI1MTY5","is_bot":false,"login":"Firoc","name":"Jason Vu"},"headRefName":"parkBackEndCRUD","number":20,"title":"Park Backend CRUD","url":"https://github.com/ucsb-cs156-s23/team03-s23-5pm-3/pull/20"},{"author":{"id":"MDQ6VXNlcjU2MDQ5Njk1","is_bot":false,"login":"Anthonypella","name":""},"headRefName":"Anthony_Frontend","number":19,"title":"Anthony frontend","url":"https://github.com/ucsb-cs156-s23/team03-s23-5pm-3/pull/19"},{"author":{"id":"MDQ6VXNlcjg2Njg0NTIy","is_bot":false,"login":"seannoh","name":"Sean Oh"},"headRefName":"Sean-BookBackend","number":18,"title":"Add Book backend CRUD files","url":"https://github.com/ucsb-cs156-s23/team03-s23-5pm-3/pull/18"},{"author":{"id":"MDQ6VXNlcjMxODM3NzIx","is_bot":false,"login":"ivanke1","name":""},"headRefName":"Ivan-Restaurant","number":17,"title":"Added Restaurant CRUD files","url":"https://github.com/ucsb-cs156-s23/team03-s23-5pm-3/pull/17"},{"author":{"id":"MDQ6VXNlcjg2NTQ4MjY0","is_bot":false,"login":"dingfan123","name":"Dingfan Zheng"},"headRefName":"Dingfan-books-frontend","number":16,"title":"fixed errors","url":"https://github.com/ucsb-cs156-s23/team03-s23-5pm-3/pull/16"}]
