
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team03-s23-5pm-3
owner: ucsb-cs156-s23
repo_name: team03-s23-5pm-3
pull_requests: [{"author":{"id":"U_kgDOB74XIA","is_bot":false,"login":"brOlivares","name":"Bryan Olivares"},"headRefName":"Bryan-frontCrud-Team01","number":21,"title":"Bryan front crud team01","url":"https://github.com/ucsb-cs156-s23/team03-s23-5pm-3/pull/21"},{"author":{"id":"MDQ6VXNlcjU2MDQ5Njk1","is_bot":false,"login":"Anthonypella","name":""},"headRefName":"Anthony_Frontend","number":19,"title":"Anthony frontend","url":"https://github.com/ucsb-cs156-s23/team03-s23-5pm-3/pull/19"}]
